variable "instance_type" {}
variable "component" {}
variable "env" {}
variable "zone_id" {}
variable "vault_token" {}
variable "subnets" {}
variable "vpc_id" {}
variable "lb_type" {}
variable "lb_needed" {}
variable "lb_subnet" {}